sudo: required

language: go

services:
  - docker
  - docker-compose

go: 
  - 1.8
  - 1.9
before_install:
  - docker-compose -f deploy/docker-compose.yml up -d
  - go get github.com/tools/godep
  - godep restore
script:
- make test-ci
- godep go test ./...
