sudo: required

language: go

services:
  - docker
  - docker-compose

go: 
  - "1.8"
  - "1.9"
  - "1.10"
before_install:
  - cp deploy/config.json config.json
  - docker-compose -f docker-compose.yml up -d
  - go get github.com/tools/godep
  - godep restore
script:
- make integration-test
